language: go

addons:
    ssh_known_hosts: localhost

before_script:
    - cp ./scripts/id_rsa* ~/.ssh/
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config

script:
    - docker build -t terrible/container scripts/
    - export CID=$(docker run -d terrible/container)
    - export PULLEY_TEST_SERVER=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${CID}) 
    - go test -v ./...
